# This file was generated by GoReleaser. DO NOT EDIT.
cask "tempogate" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "c7ba91bb874bc1f95a6cc3634e17ef58863544d893927ee23df1728505ca3f50"
      url "https://github.com/onhotpath/tempogate/releases/download/v#{version}/tempogate_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ebfa7e2a2695a1ed807e10d5c687e118c2db34d7b0c9932d9ec1d0355ad75879"
      url "https://github.com/onhotpath/tempogate/releases/download/v#{version}/tempogate_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e434ed5b45534922704cd62ccdcd430993c2aaacddf3866376239a884433f831"
      url "https://github.com/onhotpath/tempogate/releases/download/v#{version}/tempogate_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f1e210d0e6543f845f9a605f603b268c15524c2cf4b98ff06e1922b305000085"
      url "https://github.com/onhotpath/tempogate/releases/download/v#{version}/tempogate_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "tempogate"
  desc "OIDC provider & OAuth2 authorization server for self-hosted Temporal — CLI"
  homepage "https://github.com/onhotpath/tempogate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tempogate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/tempogate"]
    end
  end

  # No zap stanza required
end
