# This file was generated by GoReleaser. DO NOT EDIT.
cask "tempogate" do
  name "tempogate"
  desc "OIDC provider & OAuth2 authorization server for self-hosted Temporal — CLI"
  homepage "https://github.com/onhotpath/tempogate"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tempogate"

  on_macos do
    on_intel do
      url "https://github.com/onhotpath/tempogate/releases/download/v#{version}/tempogate_#{version}_darwin_x86_64.tar.gz"
      sha256 "2bc30efc1c6ca3135ab9a6ccd67f4365625d4e31a61ad3cfb6a93f0d7566eb73"
    end
    on_arm do
      url "https://github.com/onhotpath/tempogate/releases/download/v#{version}/tempogate_#{version}_darwin_arm64.tar.gz"
      sha256 "5c0c6891d5e89b2b19a44eda95033c0ce09fbfc09d60fd99a34e3435c34aeafe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/onhotpath/tempogate/releases/download/v#{version}/tempogate_#{version}_linux_x86_64.tar.gz"
      sha256 "ebbaac685484f11d6efcb2cfaa93a1b31ff611c68567069054ecb478e9110750"
    end
    on_arm do
      url "https://github.com/onhotpath/tempogate/releases/download/v#{version}/tempogate_#{version}_linux_arm64.tar.gz"
      sha256 "e1ddc6377d16346a7b6ddacfbeada100723101ff7387afb9705b90003260544b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/tempogate"]
    end
  end

  # No zap stanza required
end
