apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tempogate.configMapName" . }}
  labels:
    {{- include "tempogate.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.log.level | quote }}
  HTTP_LISTENER: {{ printf "%s:%v" .Values.listenAddress .Values.service.port | quote }}
  STATE_SQLITE_PATH: {{ .Values.state.sqlitePath | quote }}
  {{- with .Values.oidc.issuer }}
  OIDC_ISSUER: {{ . | quote }}
  {{- end }}
  {{- with .Values.oidc.sessionTtl }}
  OIDC_SESSION_TTL: {{ . | quote }}
  {{- end }}
  {{- with .Values.auth.clients }}
  OIDC_CLIENTS: {{ . | quote }}
  {{- end }}
  {{- with .Values.auth.allowedDomains }}
  OIDC_ALLOWED_DOMAINS: {{ join "," . | quote }}
  {{- end }}
  {{- with .Values.auth.upstream.google.authEndpoint }}
  OIDC_GOOGLE_AUTH_ENDPOINT: {{ . | quote }}
  {{- end }}
  {{- with .Values.auth.upstream.google.tokenEndpoint }}
  OIDC_GOOGLE_TOKEN_ENDPOINT: {{ . | quote }}
  {{- end }}
  {{- with .Values.auth.upstream.google.issuerUrl }}
  OIDC_GOOGLE_ISSUER_URL: {{ . | quote }}
  {{- end }}
